application: mytory-moneybook
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /downloads
  static_dir: downloads

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /pages
  static_dir: pages

- url: /fonts
  static_dir: fonts

- url: /assets
  static_dir: assets

- url: .*
  script: router.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest