#!/bin/sh
rm -rf ~/dropbox/Public/moneybook/*

rm mytory-moneybook.zip
zip mytory-moneybook.zip moneybook.html manifest.appcache config.js readme.md readme.ko.md pages/* js/production.js js/xls.js js/xlsworker.js css/production.min.css fonts/* images/icon4.png

mkdir ~/dropbox/Public/moneybook/css
cp css/production.min.css ~/dropbox/Public/moneybook/css/

mkdir ~/dropbox/Public/moneybook/fonts
cp fonts/* ~/dropbox/Public/moneybook/fonts/

mkdir ~/dropbox/Public/moneybook/pages
cp pages/* ~/dropbox/Public/moneybook/pages/

mkdir ~/dropbox/Public/moneybook/js
cp js/production.js js/xls.js js/xlsworker.js ~/dropbox/Public/moneybook/js/

mkdir ~/dropbox/Public/moneybook/images
cp images/*.png ~/dropbox/Public/moneybook/images

cp -r mytory-moneybook.zip moneybook.html manifest.appcache readme.ko.md readme.md config.js ~/dropbox/Public/moneybook/